packages:
  - npm/*
allowBuilds:
  "@parcel/watcher": false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
  "@vitest/browser-playwright": 4.1.10
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
