packages:
  - npm/*
allowBuilds:
  "@parcel/watcher": false
catalog:
  "@napi-rs/cli": 3.8.6
  "@types/node": 24.13.3
  "@vitest/browser-playwright": 4.1.11
  less: 4.8.1
  playwright: 1.62.1
  sass: 1.102.0
  tailwindcss: 4.3.3
  typescript: 7.0.2
  verdaccio: 6.9.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
  vitest: 4.1.11
  vue: 3.5.41
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
