[package]
name = "tw_migrate_planner"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
oxc-css-parser.workspace = true
oxc_sourcemap.workspace = true
serde.workspace = true
serde_json.workspace = true
tw_migrate_css.workspace = true
tw_migrate_error.workspace = true
tw_migrate_source.workspace = true
