[package]
name = "tw-migrate"
version = "0.6.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
napi.workspace = true
napi-derive.workspace = true
tw_migrate_css.workspace = true
tw_migrate_error.workspace = true
tw_migrate_planner.workspace = true
tw_migrate_source.workspace = true

[build-dependencies]
napi-build.workspace = true
